### ISSUE TITLE
Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': The RTCPeerConnection's signalingState is 'closed'.

### ISSUE THREAD

**Issue by HermanBilous** [livekit/client-sdk-js#1050]
### Describe the bug

I have this issue that I cannot reproduce at all, but get a lot of errors in sentry for. Could you please take a look and point in a direction to how to fix it. Here's the log I can extract from sentry. 

### Reproduction

N/A

### Logs

```shell
[
  {
    "level": "warning",
    "data": {
      "arguments": [
        "websocket closed",
        {
          "code": 1006,
          "identity": "<user_id>",
          "reason": "",
          "room": "room_b",
          "roomSid": "room_sid_b",
          "state": 1,
          "wasClean": false
        }
      ]
    }
  },
  {
    "level": "warning",
    "data": {
      "arguments": [
        "signal disconnected",
        {
          "identity": "<user_id>",
          "room": "room_b",
          "roomSid": "room_sid_b"
        }
      ]
    }
  },
  {
    "level": "info",
    "data": {
      "arguments": [
        "resuming signal connection, attempt 0",
        {
          "identity": "<user_id>",
          "room": "room_b",
          "roomSid": "room_sid_b"
        }
      ]
    }
  },
  {
    "level": "info",
    "data": {
      "arguments": [
        "Resuming signal connection",
        {
          "identity": "<user_id>",
          "room": "room_b",
          "roomSid": "room_sid_b"
        }
      ]
    }
  },
  {
    "level": "error",
    "data": {
      "arguments": [
        "Failed to execute 'setConfiguration' on 'RTCPeerConnection': The RTCPeerConnection's signalingState is 'closed'.",
        {
          "error": "[DOMException]",
          "identity": "<user_id>",
          "room": "room_b",
          "roomSid": "room_sid_b"
        }
      ]
    }
  },
  {
    "level": "warning",
    "data": {
      "arguments": [
        "reconnect disconnected",
        {
          "identity": "<user_id>",
          "room": "room_b",
          "roomSid": "room_sid_b"
        }
      ]
    }
  },
  {
    "level": "error",
    "data": {
      "arguments": [
        "unable to set offer",
        {
          "fields": "[Object]",
          "identity": "<user_id>",
          "room": "room_b",
          "roomSid": "room_sid_b"
        }
      ]
    }
  }
]
```
```


### System Info

```shell
Browser: any, but mostly Chrome
OS: Windows / MacOS
```

### Severity

annoyance

**Comment by lukasIO** [comment]
thanks for the report! 
which SDK version is this? Did it start popping up after a specific upgrade?

It looks like the PeerConnection went into a closed state without that triggering a reconnect (which it should). 
On a signal resume the SDK then tries to update the PeerConnection's config, but that fails as it is already closed. 
Any logs that happen before the one's you shared might be helpful here as well

**Comment by lukasIO** [comment]
Thanks for the insight, that means that the clients to perform a reconnect then after hitting that error?

**Comment by lukasIO** [comment]
Yeah, you're totally right. This code path failing should not be treated as a `SignalReconnectError` and instead force a full reconnect. Thanks for digging into this!

**Comment by lukasIO** [comment]
were you able to test the changes in the latest release?

**Comment by lukasIO** [comment]
could you provide the exact error and stack trace of an error that was present in the version released yesterday (`v2.0.5`) ?

**Comment by lukasIO** [comment]
Thanks! How do the client logs continue after the `setRemoteDescriptionError`? Just trying to make sure that the reconnect logic behaves as expected now.

**Comment by lukasIO** [comment]
@HermanBilous I'll close this issue for now. We haven't heard any similar reports. If you're still seeing this issue with the latest client+server versions feel free to let me know and I'll reopen it.

**Comment by mdelbo** [comment]
I've noticed this happen quite a bit ("livekit-client": "^2.8.0"). It seems occur when I move my laptop between home and office wifi or home and hotspot. 

In saying that, I haven't been able to reproduce it by toggling between home wifi and hotspot.

**Comment by mdelbo** [comment]
Hi @lukasIO,

I’m encountering this issue on the latest versions of livekit client & server. Logs show the same error pattern (setRemoteDescription failing due to the signaling state being closed).

Would it be possible to reopen this issue for further investigation? 

Let me know if you need more details!

```
Error: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': The RTCPeerConnection's signalingState is 'closed'.
    at PCTransport.eval (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:15208:15)
    at Generator.throw (<anonymous>)
    at rejected (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:6713:65)
```

```
InvalidStateError: Failed to execute 'addIceCandidate' on 'RTCPeerConnection': The RTCPeerConnection's signalingState is 'closed'.
    at PCTransport.eval (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:14887:24)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:6715:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:6711:12)
    at PCTransport.addIceCandidate (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:14885:12)
    at PCTransportManager.eval (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:15506:31)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:6715:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:6711:12)
    at PCTransportManager.addIceCandidate (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:15502:12)
    at client.onTrickle (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:17267:22)
    at SignalClient.handleSignalResponse (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:13868:14)
    at SignalClient.eval (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:13605:16)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:6715:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:6711:12)
    at ws.onmessage (webpack-internal:///./node_modules/livekit-client/dist/livekit-client.esm.mjs:13549:35)
```

**Comment by lukasIO** [comment]
For further investigation we'd need a way to (somewhat) reliably reproduce this issue. 

If you have a way of reproducing it on latest client feel free to open a new issue with all the details, thanks!
