### ISSUE TITLE
TrackProcessor: OverconstrainedError and TypeError Issues

### ISSUE THREAD

**Issue by robleroni** [livekit/client-sdk-js#1148]
### Describe the bug

After [#1081](https://github.com/livekit/client-sdk-js/pull/1081), using the original track as the processed track in a track processor is no longer possible.

It results in an `OverconstrainedError: The track is not connected to any source` error because the track is being [stopped ](https://github.com/livekit/client-sdk-js/blob/8ddf6a64595a01fc4d699ba14dff2c8f86949d15/src/room/track/LocalTrack.ts#L528)before trying to set the [constraints ](https://github.com/livekit/client-sdk-js/blob/8ddf6a64595a01fc4d699ba14dff2c8f86949d15/src/room/track/LocalTrack.ts#L534)again:

```javascript
const dummyProcessor: TrackProcessor<Track.Kind> = {
    name: 'Dummy',
    init: async ({ track }) => { dummyProcessor.processedTrack = track },
    restart: async () => {},
    destroy: async () => {},
}
await track.setProcessor(dummyProcessor);
```

---

I tried to clone the track as well:
```javascript
const dummyProcessor: TrackProcessor<Track.Kind> = {
    name: 'Dummy',
    init: async ({ track }) => { dummyProcessor.processedTrack = track.clone() },
    restart: async () => {},
    destroy: async () => {},
}
await track.setProcessor(dummyProcessor);
```

But this results in the following error, because `stopProcessor` [removes ](https://github.com/livekit/client-sdk-js/blob/8ddf6a64595a01fc4d699ba14dff2c8f86949d15/src/room/track/LocalTrack.ts#L532)the `processorElement` after [initialization](https://github.com/livekit/client-sdk-js/blob/8ddf6a64595a01fc4d699ba14dff2c8f86949d15/src/room/track/LocalTrack.ts#L472).

```
TypeError: Cannot read properties of undefined (reading 'srcObject')
    at attachToElement (Track.ts:344:5)
    at LocalTrack.ts:489:7
    at Generator.next (<anonymous>)
    at fulfilled (logger.ts:91:1)
```

### Reproduction

Add the above track processor.

### System Info

```shell
Brwoser: Chrome(125.0.6422.112)
livekit-client: 2.1.5
```

### Severity

blocking an upgrade

**Comment by lukasIO** [comment]
> But this results in the following error, because stopProcessor [removes ](https://github.com/livekit/client-sdk-js/blob/8ddf6a64595a01fc4d699ba14dff2c8f86949d15/src/room/track/LocalTrack.ts#L532)the processorElement after [initialization](https://github.com/livekit/client-sdk-js/blob/8ddf6a64595a01fc4d699ba14dff2c8f86949d15/src/room/track/LocalTrack.ts#L472).

good timing, I just opened #1149 to address a related issue.
