### ISSUE TITLE
LocalParticipant.createTracks can't set processors

### ISSUE THREAD

**Issue by junsumida** [livekit/client-sdk-js#1246]
### What I'm expecting

LocalParticipant.createTracks() can set processors

### What happens instead

LocalParticipant.createTracks() raises an error, `TypeError: processor.init is not a function`

### Reproduction

You can reproduce this issue by passing parameters that include `processor` to LocalParticipant.createTracks. In my case, I used `BackgroundBlur` from `track-processors-js`

### Logs

```shell
TypeError: processor.init is not a function
    at eval (livekit-client.esm.mjs:12282:27)
    at Generator.next (<anonymous>)
    at fulfilled (livekit-client.esm.mjs:6175:58)
```

`yield processor.init(processorOptions);` raises the error
 
```js
 /**
   * Sets a processor on this track.
   * See https://github.com/livekit/track-processors-js for example usage
   *
   * @experimental
   *
   * @param processor
   * @param showProcessedStreamLocally
   * @returns
   */
    setProcessor(processor_1) {
        return __awaiter(this, arguments, void 0, function(processor) {
            var _this2 = this;
            let showProcessedStreamLocally = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : true;
            return function*() {
                var _a;
                const unlock = yield _this2.processorLock.lock();
                try {
                    _this2.log.debug('setting up processor', _this2.logContext);
                    const processorElement = document.createElement(_this2.kind);
                    const processorOptions = {
                        kind: _this2.kind,
                        track: _this2._mediaStreamTrack,
                        element: processorElement,
                        audioContext: _this2.audioContext
                    };
                    yield processor.init(processorOptions);
                    _this2.log.debug('processor initialized', _this2.logContext);
                    if (_this2.processor) {
                        yield _this2.stopProcessor();
                    }
                    if (_this2.kind === 'unknown') {
                        throw TypeError('cannot set processor on track of unknown kind');
                    }
                    attachToElement(_this2._mediaStreamTrack, processorElement);
                    processorElement.muted = true;
                    processorElement.play().catch(error => _this2.log.error('failed to play processor element', Object.assign(Object.assign({}, _this2.logContext), {
                        error
                    })));
                    _this2.processor = processor;
                    _this2.processorElement = processorElement;
                    if (_this2.processor.processedTrack) {
                        for (const el of _this2.attachedElements) {
                            if (el !== _this2.processorElement && showProcessedStreamLocally) {
                                detachTrack(_this2._mediaStreamTrack, el);
                                attachToElement(_this2.processor.processedTrack, el);
                            }
                        }
                        yield(_a = _this2.sender) === null || _a === void 0 ? void 0 : _a.replaceTrack(_this2.processor.processedTrack);
                    }
                    _this2.emit(TrackEvent.TrackProcessorUpdate, _this2.processor);
                } finally {
                    unlock();
                }
            }();
        });
    }
```

### System Info

OS

```shell
Ubuntu 22.04.4 LTS
```

from package.json

```
    "@livekit/components-core": "0.10.5",
    "@livekit/components-react": "2.3.6",
    "@livekit/components-styles": "1.0.12",
    "@livekit/track-processors": "0.3.2",
    "livekit-client": "2.4.0",
```

Browser

```
Google Chrome 128.0.6613.84（Official Build）
```

### Severity

serious, but I can work around it

### Additional Information

`LocalParticipant.createTracks()` uses `mergeDefaultOptions()` to create `mergedOptions`, which internally calls `cloneDeep()`. However, `cloneDeep()` does not copy functions.

```ts
  async createTracks(options?: CreateLocalTracksOptions): Promise<LocalTrack[]> {
    const mergedOptions = mergeDefaultOptions(
      options,
      this.roomOptions?.audioCaptureDefaults,
      this.roomOptions?.videoCaptureDefaults,
    );
```

https://github.com/livekit/client-sdk-js/blob/bf7fb5d1c5df264fd1ce5adfc951bbec73fbfd77/src/room/participant/LocalParticipant.ts#L489C27-L489C46

`trackOptions` directly uses `mergedOptions`:

```ts
        let trackOptions = isAudio ? mergedOptions!.audio : mergedOptions!.video;
        if (trackOptions.processor) {
          if (track instanceof LocalAudioTrack) {
            await track.setProcessor(trackOptions.processor as TrackProcessor<Track.Kind.Audio>);
          } else {
            await track.setProcessor(trackOptions.processor as TrackProcessor<Track.Kind.Video>);
          }
        }
```

https://github.com/livekit/client-sdk-js/blob/bf7fb5d1c5df264fd1ce5adfc951bbec73fbfd77/src/room/participant/LocalParticipant.ts#L523

For your information:

`createLocalTracks()` in `create.ts` does something similar but uses the original argument directly, and this works
https://github.com/livekit/client-sdk-js/blob/main/src/room/track/create.ts#L58

**Comment by lukasIO** [comment]
Thank you for the detailed report! 

I opened a PR to address the issue. 
The behaviour difference to `createLocalTracks` was a bug in `createLocalTracks` so the PR also addresses that. 
Can you test with the changes of #1247 and confirm that it fixes the issue for you?

**Comment by junsumida** [comment]
Thank you for your quick response. 
I've confirmed that the problem is fixed with the branch :smile:
