### ISSUE TITLE
ScalabilityMode is not defined

### ISSUE THREAD

**Issue by crapthings** [livekit/client-sdk-js#814]
### Describe the bug

this show up when upgraded from 1.12.1 to 1.12.2

### Reproduction

ScalabilityMode is not defined

### System Info

```shell
livekit client js: 1.12.2
```

### Severity

annoyance

**Comment by lukasIO** [comment]
Hi, 
could you please provide the stack trace for where this error shows up? 

If it does not show up in the `/example` in this folder, please also provide steps to reproduce the bug.

**Comment by crapthings** [comment]
```js
  if (svc) {
    // svc layers
    /* @ts-ignore */
    const sm = new ScalabilityMode(encodings[0].scalabilityMode);
    const layers = [];
    for (let i = 0; i < sm.spatial; i += 1) {
      layers.push(
        new VideoLayer({
          quality: VideoQuality.HIGH - i,
          width: width / 2 ** i,
          height: height / 2 ** i,
          bitrate: encodings[0].maxBitrate ? encodings[0].maxBitrate / 3 ** i : 0,
          ssrc: 0,
        }),
      );
    }
    return layers;
  }
```

```
LocalVideoTrack.ts:486 Uncaught (in promise) ReferenceError: ScalabilityMode is not defined
    at videoLayersFromEncodings (LocalVideoTrack.ts:486:16)
    at LocalParticipant.<anonymous> (LocalParticipant.ts:711:20)
    at Generator.next (<anonymous>)
    at fulfilled (DefaultReconnectPolicy.ts:33:2)
    at meteor.js?hash=7dd187e6c4c7dc8731ddaf9d1d993d3c3ba5a732:1343:22
videoLayersFromEncodings @ LocalVideoTrack.ts:486
(anonymous) @ LocalParticipant.ts:711
fulfilled @ DefaultReconnectPolicy.ts:33
(anonymous) @ meteor.js?hash=7dd187e6c4c7dc8731ddaf9d1d993d3c3ba5a732:1343
await in (anonymous) (async)
eval @ push-video.js:101
commitHookEffectListMount @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:124444
commitPassiveMountOnFiber @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:126220
commitPassiveMountEffects_complete @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:126185
commitPassiveMountEffects_begin @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:126172
commitPassiveMountEffects @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:126160
flushPassiveEffectsImpl @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:128333
flushPassiveEffects @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:128278
performSyncWorkOnRoot @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:127370
flushSyncCallbacks @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:113336
commitRootImpl @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:128253
commitRoot @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:127976
finishConcurrentRender @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:127275
performConcurrentWorkOnRoot @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:127103
workLoop @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:131503
flushWork @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:131476
performWorkUntilDeadline @ modules.js?hash=a686d9822697c9a800de028e5a51f7f12b526765:131770

```

**Comment by davidzhao** [comment]
@crapthings which browser are you seeing this behavior?

**Comment by crapthings** [comment]
> @crapthings which browser are you seeing this behavior?

Chrome latest

**Comment by davidzhao** [comment]
Thanks. I see the issue. There was a missing import in the code. Will fix.
