### ISSUE TITLE
[React Native] Property 'TextDecoder' doesn't exist

### ISSUE THREAD

**Issue by wjaykim** [livekit/client-sdk-js#860]
### Describe the bug

All functionality is broken in React Native with latest client-sdk-js version(1.13.0).

I guess this happened after this library migrated to protobuf-es(https://github.com/livekit/client-sdk-js/pull/700). protobuf-es includes TextDecoder API(https://github.com/bufbuild/protobuf-es/blob/main/packages/protobuf/src/binary-encoding.ts#L568), which is not implemented in React Native.

### Reproduction

Use livekit-client-js 1.13.0 in React Native

### Logs

```shell
WARN  websocket closed {"ev": {"code": 1001, "isTrusted": false, "reason": "Stream end encountered"}}
 WARN  Possible Unhandled Promise Rejection (id: 9):
ReferenceError: Property 'TextDecoder' doesn't exist
ReferenceError: Property 'TextDecoder' doesn't exist
    at F (http://10.68.140.18:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=us.zep.mobile:394731:197)
    at readerFactory (http://10.68.140.18:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=us.zep.mobile:394944:23)
    at fromBinary (http://10.68.140.18:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=us.zep.mobile:394351:53)
    at fromBinary (http://10.68.140.18:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=us.zep.mobile:399729:37)
    at ?anon_0_ (http://10.68.140.18:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=us.zep.mobile:402520:38)
    at next (native)
    at anonymous (http://10.68.140.18:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=us.zep.mobile:397726:41)
    at tryCallTwo (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)
    at gt (http://10.68.140.18:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=us.zep.mobile:397705:38)
    at anonymous (http://10.68.140.18:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=us.zep.mobile:402512:26)
    at call (native)
    at dispatchEvent (http://10.68.140.18:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=us.zep.mobile:36620:31)
    at anonymous (http://10.68.140.18:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=us.zep.mobile:37599:31)
    at apply (native)
    at emit (http://10.68.140.18:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=us.zep.mobile:2513:40)
    at apply (native)
    at __callFunction (http://10.68.140.18:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=us.zep.mobile:3382:36)
    at anonymous (http://10.68.140.18:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=us.zep.mobile:3102:31)
    at __guard (http://10.68.140.18:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=us.zep.mobile:3319:15)
    at callFunctionReturnFlushedQueue (http://10.68.140.18:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=us.zep.mobile:3101:21)
```

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 83.66 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 3.6.1 - ~/.nvm/versions/node/v18.16.1/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    Watchman: 2023.04.10.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.5.1
  npmPackages:
    livekit-client: 1.13.0 => 1.13.0
```

### Severity

annoyance

**Comment by wjaykim** [comment]
I was able to fix the issue via installing polyfill(https://www.npmjs.com/package/text-encoding-polyfill).

Also needed to add following line:
```js
import 'text-encoding-polyfill';
```
